name: Bug report
description: Report a reproducible problem
labels: [bug]
body:
  - type: textarea
    id: desc
    attributes:
      label: Describe the bug
      description: What happened and what did you expect?
      placeholder: Clear and concise description
    validations:
      required: true
  - type: textarea
    id: repro
    attributes:
      label: Reproduction steps
      description: Minimal steps/code to reproduce
      placeholder: 1) … 2) … 3) …
    validations:
      required: true
  - type: input
    id: versions
    attributes:
      label: Versions / env
      placeholder: OS, Node, Python, Ollama, Browser
  - type: textarea
    id: logs
    attributes:
      label: Logs / screenshots
      render: shell
