blank_issues_enabled: false
contact_links:
  - name: Feedback & Ideas (Discussions)
    url: https://github.com/avinashpentester/aivp/discussions
    about: Share general feedback or brainstorming here